# Generated by Django 3.1.7 on 2021-03-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_avatar_user'),
        ('books', '0003_auto_20210323_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.avatar'),
        ),
    ]
